// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MinecraftLogAnalyzer
{
    public partial class PlaytimePredictor
    {
        /// <summary>
        /// model input class for PlaytimePredictor.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"name")]
            public string Name { get; set; }

            [ColumnName(@"LoginTime")]
            public DateTime LoginTime { get; set; }

            [ColumnName(@"LogOutTime")]
            public DateTime LogOutTime { get; set; }

            [ColumnName(@"Duration")]
            public string Duration { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PlaytimePredictor.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"name")]
            public float[] Name { get; set; }

            [ColumnName(@"LoginTime")]
            public float LoginTime { get; set; }

            [ColumnName(@"LogOutTime")]
            public float LogOutTime { get; set; }

            [ColumnName(@"Duration")]
            public string Duration { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PlaytimePredictor.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
